spring.datasource.url=${DB_URL:jdbc:mysql://mysql-1bffe44e-anurag-aea9.h.aivencloud.com:20157/defaultdb?sslMode=REQUIRED}
spring.datasource.username=${DB_USERNAME:avnadmin}
spring.datasource.password=${DB_PASSWORD:replace-with-your-db-password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=${JPA_HIBERNATE_DDL_AUTO:update}
